---
title: "Dreamlet analysis of single cell pseudo-bulk data"
subtitle: ''
author: "Developed by [Gabriel Hoffman](http://gabrielhoffman.github.io/)"
date: "Run on `r Sys.time()`"
documentclass: article
output:
  html_document:
    toc: true
    toc_float: true
---

<!---

cd /Users/gabrielhoffman/workspace/repos/variancePartition/vignettes

rmarkdown::render("dreamlet.Rmd")


 devtools::reload("/Users/gabrielhoffman/workspace/repos/dreamlet")

devtools::reload("/Users/gabrielhoffman/workspace/repos/zenith")



--->



```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning=FALSE,
  message=TRUE,
  error = FALSE,
  tidy = FALSE,
  dev = c("png", "pdf"),
  cache = TRUE)
```

## Preprocess data
```{r preprocess.data}

library(dreamlet)
library(muscat)
library(ExperimentHub)
library(cowplot)
library(zenith)

eh <- ExperimentHub()
# query(eh, "Kang")

(sce <- eh[["EH2259"]])

sce <- sce[rowSums(counts(sce) > 0) > 0, ]

library(scater)
qc <- perCellQCMetrics(sce)

# remove cells with few or many detected genes
ol <- isOutlier(metric = qc$detected, nmads = 2, log = TRUE)
sce <- sce[, !ol]

sce <- sce[rowSums(counts(sce) > 1) >= 10, ]
sce <- computeLibraryFactors(sce)
sce <- logNormCounts(sce)
```

## Aggregate to pseudobulk
```{r aggregate}
sce$id <- paste0(sce$stim, sce$ind)
(sce <- prepSCE(sce, 
    kid = "cell", # subpopulation assignments
    gid = "stim",  # group IDs (ctrl/stim)
    sid = "id",   # sample IDs (ctrl/stim.1234)
    drop = TRUE)) 

pb <- aggregateData(sce,
    assay = "counts", fun = "sum",
    by = c("cluster_id", "sample_id"))

# one sheet per subpopulation
assayNames(pb)
```

# dreamlet code
## Process pseudo bulk from each assay
```{r dreamlet, fig.width=9, fig.height=10}
# Normalize and apply voom
res.proc = processAssays( pb, ~ group_id)

res.proc

plotVoom( res.proc)
```


## Run variancePartition analysis
```{r vp}
vp.lst = fitVarPart( res.proc, ~ group_id)
```

### variancePartition plots for each cell type
```{r plot.fitVarPart, fig.width=9, fig.height=10}
fitList = lapply( names(vp.lst), function(cellType){
	plotVarPart(vp.lst[[cellType]], main=cellType)
	})

plot_grid(plotlist = fitList, ncol=3)
```

## Run dreamlet
```{r test}
res.dl = dreamlet( res.proc, ~ group_id)
```

### Volcano plot for each cell type
```{r plotVolcano, fig.width=9, fig.height=10}
plotVolcano_grid( res.dl, coef = 'group_idstim' )
```

## Extract results
```{r extract}
fit = res.dl[["B cells"]]
topTable(fit, coef = 'group_idstim' )
```

### Forrest plot 
```{r forrest}
plotForrest( res.dl, coef = 'group_idstim', gene = 'IRF7')
```



# Gene set analysis using zenith
```{r zenith}
# Load Gene Ontology database 
# use gene SYMBOL
go.gs = get_GeneOntology(to="SYMBOL")
     
# convert from GeneSetCollection to list used by camera and zenith
geneSets_GO = recodeToList( go.gs )

# Run zenith gene set analysis on result of dreamlet
res_zenith = zenith_gsa(res.dl, coef = 'group_idstim', geneSets_GO)

# examine results
head(res_zenith)
```

## Heatmap of top genesets
```{r heatmap, fig.height=14, fig.width=5}
plotZenithResults(res_zenith)
```




































