# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cbind_list_of_sparseMatrix <- function(resList, verbose) {
    .Call('_dreamlet_cbind_list_of_sparseMatrix', PACKAGE = 'dreamlet', resList, verbose)
}

rowSums_by_chunk_sparse <- function(data, idxlst, verbose) {
    .Call('_dreamlet_rowSums_by_chunk_sparse', PACKAGE = 'dreamlet', data, idxlst, verbose)
}

rowSums_by_chunk <- function(data, idxlst, verbose) {
    .Call('_dreamlet_rowSums_by_chunk', PACKAGE = 'dreamlet', data, idxlst, verbose)
}

aggregateByColnames <- function(resList, idLst, grpUniq) {
    .Call('_dreamlet_aggregateByColnames', PACKAGE = 'dreamlet', resList, idLst, grpUniq)
}

