# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rowSums_by_chunk_sparse <- function(data, idxlst) {
    .Call('_dreamlet_rowSums_by_chunk_sparse', PACKAGE = 'dreamlet', data, idxlst)
}

rowSums_by_chunk <- function(data, idxlst) {
    .Call('_dreamlet_rowSums_by_chunk', PACKAGE = 'dreamlet', data, idxlst)
}

